name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.10.0
      - uses: rdunnington/setup-wabt-action@master
        with:
          wabt-version: "1.0.31"
      - run: zig build test
